name: Deploy DAGs to Airflow Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync DAGs to server via rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz --delete --exclude='.github'
          path: ./
          remote_path: ~/airflow-project/airflow-dags/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SERVER_PORT }}
