name: Deploy DAGs to Airflow Server

on:
  push:
    branches:
      - main  # or whatever your main DAG branch is

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync DAGs to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/airflow-project/airflow-dags
            git pull origin main
            find . -name '*.py' -exec touch {} +
